# -*- coding: utf-8 -*-
"""Hackathon (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvqpHQoPMG-nqbRhicMQ089OBS38j5C3
"""

import cv2
import time
import math as m
# import mediapipe as mp
import os

import cv2
from IPython.display import display, Image
import io


#print("asdfasd")
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

image_count = 0

while image_count<=10:
    ret, frame = cap.read()
    if ret:
        cv2.imshow("Webcam", frame)

        # Save the captured image to a buffer
        ret, buffer = cv2.imencode('.jpg', frame)
        if not ret:
            print("Error: Could not encode frame.")
            break

        # Display the captured image in the notebook
        display(Image(data=buffer.tobytes()))

        # Save the captured image to a file
        image_filename = f"image_{image_count}.jpg"
        cv2.imwrite('/Users/home/Downloads/proj_face_recog/images' + image_filename, frame)

        image_count += 1

        # Exit the loop if the 'q' key is pressed
        if cv2.waitKey(1000) & 0xFF == ord('q'):
            break
    else:
        print("Error: Could not read frame from camera.")
        break

# Release the camera and close OpenCV windows
cap.release()
cv2.destroyAllWindows()

